
CREATE TABLE NETFLIX(ID INTEGER PRIMARY KEY,NOMBRE VARCHAR2(20), SINOPSIS VARCHAR2(20));

CREATE SEQUENCE SEC_NETFLIX
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

            

CREATE OR REPLACE PROCEDURE GUARDAR_PELICULA(MY_ID OUT INTEGER, 
             MY_NOMBRE IN VARCHAR2,MY_SINOPSIS IN VARCHAR2)
              AS
              BEGIN
              SELECT SEC_NETFLIX.NEXTVAL INTO MY_ID FROM DUAL;
              INSERT INTO NETFLIX(ID,NOMBRE,SINOPSIS)
              VALUES (MY_ID,MY_NOMBRE,MY_SINOPSIS);
              END;
              /
              
              SELECT *FROM NETFLIX;